apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "a5c0afc2-4793-42b8-8d1a-be73c95026a5"
      - op: replace
        path: /spec/parameters/tenantId
        value: "488cd0ad-9f25-4676-a378-b80a1063b0ab"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://mercurybackupsstaging-Cv1N.blob.core.windows.net/customer1"
