apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "${AKS_KEYVAULT_IDENTITY_CLIENT_ID}"
      - op: replace
        path: /spec/parameters/tenantId
        value: "${AZURE_TENANT_ID}"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://orionbackupsstgcv1n.blob.core.windows.net/customer1"
  - target:
      kind: Ingress
      name: customer1-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "customer1.dcinfrastructures.io"
      - op: replace
        path: /spec/rules/0/host
        value: "customer1.dcinfrastructures.io"
