apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secrets.yaml

patches:
  - target:
      kind: SecretProviderClass
      name: grafana-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "${AKS_KEYVAULT_IDENTITY_CLIENT_ID}"
      - op: replace
        path: /spec/parameters/keyvaultName
        value: "kv-orion-prod"
      - op: replace
        path: /spec/parameters/tenantId
        value: "${AZURE_TENANT_ID}"

configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
